humansis/api

- src/BeneficiaryBundle/Repository/CampRepository.php
- src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
> fix conflict about camp with the same name and different location

- app/DoctrineMigrations/Version20191024100735.php
- src/VoucherBundle/Controller/BookletController.php
- src/VoucherBundle/Entity/Booklet.php
- src/VoucherBundle/Repository/BookletRepository.php
- src/VoucherBundle/Utils/BookletService.php
- src/VoucherBundle/Utils/VoucherService.php
- tests/VoucherBundle/Controller/BookletControllerTest.php
- tests/VoucherBundle/Controller/VoucherControllerTest.php
> Dev booklet general fix

- src/CommonBundle/DataFixtures/LocationFixtures.php
run `php bin/console doctrine:fixtures:load --append --group=location`
> Allow to append location fixtures

- src/VoucherBundle/Repository/BookletRepository.php
- src/VoucherBundle/Utils/BookletService.php
Added entity manager clear after flush to save memory.
Created query to get all inserted booklets after the last id given.
> Voucher creation upgrade

- src/CommonBundle/Controller/ExportController.php
- src/VoucherBundle/Utils/BookletService.php
- src/VoucherBundle/Utils/VoucherService.php
Add filtered export for vouchers.
Fix export problems.
Closes issue 184 in humansis/front
> Voucher export

- src/CommonBundle/Controller/ExportController.php
- src/VoucherBundle/Repository/VoucherRepository.php
- src/VoucherBundle/Utils/VoucherService.php
Add fast streamed alternative for csv filtered exports. Other export types will still use the general method.
> Fast csv alternative voucher export

- app/DoctrineMigrations/Version20200304150214.php
- src/DistributionBundle/Resources/views/Pdf/distribution.html.twig
- src/DistributionBundle/Resources/views/Pdf/distributions.html.twig
- src/DistributionBundle/Utils/DistributionService.php
- src/ProjectBundle/Entity/Project.php
- src/ProjectBundle/Utils/ProjectService.php
- tests/ProjectBundle/Controller/ProjectControllerTest.php
branch was merged accidentaly merged into develop instead of dev
> remerge Internal ID into dev

- src/CommonBundle/DataFixtures/UserFixtures.php
- src/UserBundle/Entity/User.php
there were missing access right for most testing user accounts
> #37 PIN-81 Added: user access rights to more countries

- src/CommonBundle/DataFixtures/VendorFixtures.php
- tests/VoucherBundle/Controller/VoucherControllerTest.php
> #32 PIN-81 Fixed: unique FK in vendors

- src/BeneficiaryBundle/Controller/CountrySpecificController.php
- src/BeneficiaryBundle/Controller/HouseholdController.php
- src/BeneficiaryBundle/Controller/InstitutionController.php
- src/CommonBundle/Controller/CommonController.php
- src/CommonBundle/Controller/ExportController.php
- src/CommonBundle/Controller/LocationController.php
- src/DistributionBundle/Controller/CriteriaDistributionController.php
- src/DistributionBundle/Controller/DistributionController.php
- src/ProjectBundle/Controller/ProjectController.php
- src/TransactionBundle/Controller/TransactionController.php
- src/UserBundle/Controller/UserController.php
- src/VoucherBundle/Controller/BookletController.php
- src/VoucherBundle/Controller/ProductController.php
- src/VoucherBundle/Controller/VendorController.php
- src/VoucherBundle/Controller/VoucherController.php
In swagger documentation miss information about country, which is required for most of requests.
> added missing header definition of country to Swagger

- src/BeneficiaryBundle/Controller/HouseholdController.php
- src/BeneficiaryBundle/Utils/HouseholdCSVService.php
- src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
dependency https://github.com/humansis/front/pull/175
> [!!!][FEATURE] Add column mapping on household importing process

- app/config/security.yml
- src/BeneficiaryBundle/Controller/BeneficiaryController.php
- src/DistributionBundle/Controller/DistributionController.php
- src/ProjectBundle/Controller/ProjectController.php
- src/UserBundle/Controller/UserController.php
- src/VoucherBundle/Controller/BookletController.php
Routes used in offline app have your own URL with prefix offline-app. It will allow simplier refactorization.
> Added routes for offline app

- src/VoucherBundle/Controller/SmartcardController.php
- tests/VoucherBundle/Controller/SmartcardControllerTest.php
> #79 PIN-45: Removed depositorId from request inputs. Depositor is logged user

- src/VoucherBundle/Controller/SmartcardController.php
- tests/VoucherBundle/Controller/SmartcardControllerTest.php
It should be allowed for offline app
> #79 PIN-45: Changed route for deposit money

- src/BeneficiaryBundle/Entity/Household.php
- src/BeneficiaryBundle/Utils/HouseholdService.php
- tests/BeneficiaryBundle/Controller/HouseholdControllerTest.php
missing saving data from update request
> PIN-167: fixed HH edit support organization name

- docker-compose.demo.yml.dist
- docker-compose.prod.yml.dist
- docker-compose.stage.yml.dist
- docker-compose.yml.dist
- docker/dev/phpmyadmin/config.user.inc.php
- docker/prod/phpmyadmin/config.user.inc.php
- docker/stage/phpmyadmin/config.user.inc.php
Added custom configuration for phpmyadmin. 
- nonpaginated list of tables
- nongrouped databases
> Changed configuration for dockerized phpmyadmin

- src/ProjectBundle/DBAL/SectorEnum.php
"Camp Coordination and Management" and "Early Recovery".
> PIN-206: added missing Sector Names

- src/VoucherBundle/Repository/SmartcardPurchaseRepository.php
- tests/VoucherBundle/Controller/SmartcardControllerTest.php
> PIN-587: fixed purchase counting and its test

- .travis.yml
- apply_env_config.sh
- clean_database.sh
- clear_cache.sh
- deploy.sh
- docker/docker-compose.yml.demo
- docker/docker-compose.yml.dev
- docker/docker-compose.yml.prod
- docker/docker-compose.yml.stage
- docker/docker-compose.yml.test
- get_db.sh
- get_info.sh
- sync_excludes
check, that ALL the env variables are present in travis-ci.com build settings
> Change deploy procedure, add scripts

- src/BeneficiaryBundle/Entity/Beneficiary.php
- src/BeneficiaryBundle/Model/Vulnerability/ConditionEnum.php
- src/BeneficiaryBundle/Model/Vulnerability/Resolver.php
- src/BeneficiaryBundle/Resources/config/vulnerability/scoring_SYR.csv
- tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
- tests/BeneficiaryBundle/Resources/Vulnerability/resolver_scoring_SYR.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_bad_format.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_bad_format_score_value.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_correct.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_missing_condition_value.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_missing_row.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_missing_score_value.csv
- tests/BeneficiaryBundle/Resources/Vulnerability/scoring_unknown_condition.csv
Please merge this pull request AFTER resolving this pull request:
https://github.com/humansis/api/pull/257
> PIN-656: Vulnerability household members

- src/BeneficiaryBundle/Controller/BeneficiaryController.php
- src/BeneficiaryBundle/Controller/CommunityController.php
- src/BeneficiaryBundle/Controller/HouseholdController.php
- src/BeneficiaryBundle/Controller/InstitutionController.php
> PIN-621: unaccessable bnf after archivation

- app/DoctrineMigrations/Version20201112120130.php
- app/DoctrineMigrations/Version20201112130316.php
- src/VoucherBundle/Controller/SmartcardController.php
- src/VoucherBundle/DTO/PurchaseDetail.php
- src/VoucherBundle/DTO/PurchaseRedeemedBatch.php
- src/VoucherBundle/DTO/PurchaseRedemptionBatch.php
- src/VoucherBundle/DTO/PurchaseSummary.php
- src/VoucherBundle/Entity/SmartcardPurchase.php
- src/VoucherBundle/Entity/SmartcardRedemptionBatch.php
- src/VoucherBundle/Repository/SmartcardPurchaseRepository.php
- src/VoucherBundle/Repository/SmartcardRedemptionBatchRepository.php
- tests/VoucherBundle/Controller/SmartcardControllerTest.php
remake Smartcard redemption feature to its own entity
> PIN-762: smarcard batch

- src/VoucherBundle/Controller/SmartcardController.php
- src/VoucherBundle/DTO/PurchaseDetail.php
- src/VoucherBundle/Entity/SmartcardRedemptionBatch.php
- tests/VoucherBundle/Controller/SmartcardControllerTest.php
and numeric value serialization
> PIN-764: redemption batch ID

- src/BeneficiaryBundle/Repository/CommunityRepository.php
- src/BeneficiaryBundle/Repository/InstitutionRepository.php
- src/BeneficiaryBundle/Utils/CommunityService.php
- src/BeneficiaryBundle/Utils/InstitutionService.php
> Revert "PIN-851: filter comm inst"

- src/DistributionBundle/Utils/DistributionService.php
It looks like fix removed accidentaly by complex merge but I dont know if you do additional changes. please check it more deeply.
> PIN-1003: export project bug
